language: node_js
dist: trusty
node_js:
  - 8
cache:
  yarn: true
install:
  - yarn
  - cd example && yarn && cd ..
script:
  - yarn build
  - cd example && yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GH_TOKEN
  target-branch: published
  on:
    branch: master
